Add typescript express example
serverless/examples pull request #577
Opened 2021-01-24 16:08 UTC by HoseungJang

Hi. I added very simple express application example.
Thanks!

2021-01-27 08:34 UTC, pgrzesik requested changes
Thanks @HoseungJang, it looks good, however, as I'm not expert on Typescript, I'll see if we can get another review. Also, please see a few of my comments

2021-01-27 08:34 UTC, pgrzesik commented on aws-node-typescript-express/README.md
> +framework: v1
We should specify `v2` here

2021-01-27 08:34 UTC, pgrzesik commented on aws-node-typescript-express/serverless.yml
> +provider:
Let's add `provider.apiGateway.shouldStartNameWithService: true` and `provider.lambdaHashingVersion: 20201221` to avoid deprecations and opt-in to use these options that will be defaults in v3

2021-01-27 08:34 UTC, pgrzesik commented on aws-node-typescript-express/src/app.ts
> +  console.log("asdf")
I guess this log could be removed or it was intended to leave it here?

2021-01-27 08:35 UTC, pgrzesik commented
Hello @bartheletf, sorry for messaging you out of the blue, but knowing that you're a TS expert, do you think you'll have a chance to take a look at this example from that perspective? Thanks in advance :bow:

2021-01-27 08:38 UTC, HoseungJang commented on aws-node-typescript-express/src/app.ts
> +  console.log("asdf")
Oh, sorry I forgot to remove it

2021-01-27 08:50 UTC, HoseungJang commented on aws-node-typescript-express/serverless.yml
> +provider:
Thanks!

2021-01-27 08:52 UTC, HoseungJang commented on aws-node-typescript-express/README.md
> +framework: v1
is it supposed to be the current installed version of ```serverless```?

2021-01-29 11:55 UTC, pgrzesik commented
Thank you @HoseungJang - I believe it might be a bit better if you'd move your example to your own repository and list it under `Community Examples` - would you be okay with that?

2021-01-29 12:18 UTC, HoseungJang commented
Hi @pgrzesik 
I don't mind that opinion, but could you tell me about the reason of it?

2021-01-31 12:30 UTC, pgrzesik commented
Sure @HoseungJang - as you're the only author of this example, it feels to me that it belongs more into `Community Examples`. Additionally, I'm not a TypeScript expert, which makes it a bit harder for me to assess the quality and confidently introduce it as a part of this repository.

2021-01-31 13:18 UTC, HoseungJang commented
Thank you for answer @pgrzesik .
Then how I move this example to ```Community Examples```? just add it to ```community-examples.json```?
and can I do this job on this PR? or should I open a new one?

2021-02-01 10:05 UTC, pgrzesik commented
Yes, you should add it to the mentioned file. You can totally do that as a part of this PR. Thank you :bow:

2021-02-02 05:03 UTC, HoseungJang commented
Hi @pgrzesik !
I'm all done. Could you check it again?
But I'm sorry that it may take a long time to complete CI, it may be because I live far from you.

2021-02-02 08:48 UTC, pgrzesik commented
Thank you @HoseungJang - I've forgot that the README has to be updated manually, sorry about that. Could you run `npm run docs` locally so it will update the `README.md` file with your entry?

Thanks :bow:

2021-02-02 15:09 UTC, HoseungJang commented
Thank you @pgrzesik .
Could you check again please?

2021-02-02 20:12 UTC, pgrzesik approved these changes
Thank you @HoseungJang :bow:

2021-02-02 20:12 UTC, merged