Ruby/Sinatra/DynamoDB example
serverless/examples pull request #600
Opened 2021-03-19 17:30 UTC by icole

This is inspired from @pgrzesik's great aws-python-flask-api example that I ported to Ruby/Sinatra. I am still learning serverless, so welcome any feedback or suggestions on if this could have been implemented any better.

2021-04-09 10:22 UTC, pgrzesik requested changes
Thank you @icole :bow: I'm sorry to not get to this sooner, but I've somehow missed the notification and noticed it only now. I've quickly tested it and it works great :+1: Let's just remove the `serverless.template.yml` and we're good to go

2021-04-09 10:22 UTC, pgrzesik commented on aws-ruby-sinatra-dynamodb-api/serverless.template.yml
> +name: aws-ruby-sinatra-dynamodb-api
I think we can remove this file, as this was additionally needed to publish an example as a template for https://app.serverless.com/

2021-05-01 00:49 UTC, icole commented
@pgrzesik Apologies for my delay now! I as well did not seem to get a notification. I went ahead and removed that file. Please let me know if there is anything else I can do.

2021-05-03 08:01 UTC, pgrzesik approved these changes
Thank you @icole - awesome job :clap:

2021-05-03 08:01 UTC, merged