Add serverless ruby dynamodb cron example
serverless/examples pull request #614
Opened 2021-06-05 08:46 UTC by Pigius

# Big picture behind

Currently, there aren't many examples of using the serverless approach with Ruby for AWS. Ruby is a great and mature language with a great community and lots of gems.

Obviously, for cron jobs, there are enormous amount of possibilities in both Ruby/Rails, like gem [whenever](https://github.com/javan/whenever), however, my goal, is to show that is pretty easy with Serverless Framework with AWS.

# General message

I've created a simple example of scheduled cron (using the serverless `schedule` event), with AWS Lambda and DynamoDB.

The purpose of the service is a scheduled cron that triggers AWS Lambda every 30 minutes, which creates a new record in the DynamoDB database with meal order data.

The diagram could be found here:

![aws-ruby-cron-diagram](https://user-images.githubusercontent.com/8863200/120885548-ef6ecd00-c5e9-11eb-90f8-ab2116d28901.png)

Extra points:

- The readme is quite extensive, and I hope, that it will be easy to understand everything.
- Used the Ruby.27 runtime, as for the Ruby2.5 will be End of Support at the end of August. 
- The DynamoDB table name is a combination of service name and stage.

2021-06-08 20:05 UTC, pgrzesik requested changes
Thanks @Pigius for proposing this PR, great work :+1: I've added a few notes, please let me know what do you think :bow:

2021-06-08 20:05 UTC, pgrzesik commented on aws-ruby-cron-with-dynamodb/serverless.yml
> +  profile: ${self:custom.deployment.profile.${self:provider.stage}}
Let's remove setting profile in this way - it is encouraged to use `AWS_PROFILE` env variable instead of setting it on provider level.

2021-06-08 20:05 UTC, pgrzesik commented on aws-ruby-cron-with-dynamodb/serverless.yml
> +  region: ${self:custom.deployment.region.${self:provider.stage}}
Just a note - this will be overridden by CLI option if one will be provided

2021-06-08 20:05 UTC, pgrzesik commented on aws-ruby-cron-with-dynamodb/package.json
> +    "serverless-export-env": "github:arabold/serverless-export-env"
Is there a reason as to why it's not using the version released to npm?

2021-06-09 13:39 UTC, Pigius commented on aws-ruby-cron-with-dynamodb/serverless.yml
> +  iamRoleStatements:
Agree. Done.

2021-06-09 13:40 UTC, Pigius commented on aws-ruby-cron-with-dynamodb/serverless.yml
> +    Stage: ${self:provider.stage}
Nice, did not know that before. Fixed.

2021-06-09 13:40 UTC, Pigius commented on aws-ruby-cron-with-dynamodb/serverless.yml
> +  stage: ${opt:stage, 'dev'}
Done

2021-06-09 13:41 UTC, Pigius commented on aws-ruby-cron-with-dynamodb/serverless.yml
> +  region: ${self:custom.deployment.region.${self:provider.stage}}
I see. I've decided to get rid of the deployment file. Don't think we need it. WDYT?

2021-06-09 13:41 UTC, Pigius commented on aws-ruby-cron-with-dynamodb/package.json
> +    "serverless-export-env": "github:arabold/serverless-export-env"
Good catch, fixed that to fetch it from the NPM version.

2021-06-09 13:48 UTC, Pigius commented
@pgrzesik I am more than happy that you like my contribution. I tried my best. Thanks to this feedback I also learned a little bit more about Serverless Framework. Thank you.

## Additional things
- I removed `deployment.yml`, it is unnecessary for us, and would only be overwritten via the CLI.
- I increased the `memorySize` to 256 MB, because Ruby likes memory ;) 
 - Increased the `timeout` to 10 seconds, to avoid timeouts that happen from time to time.

I am waiting for the next round of PR feedback, so we can merge it soon :)

2021-06-14 07:24 UTC, pgrzesik requested changes
Thanks @Pigius - awesome job :clap: I only have one minor suggestion and we're good to go :+1:

2021-06-14 07:24 UTC, pgrzesik commented on aws-ruby-cron-with-dynamodb/README.md
> +for deploying to the specific stage, let's say `staging` (those are defined in `config/deployment.yml`) do:
Let's remove reference to `config/deployment.yml` as that file is no longer used

2021-06-14 07:37 UTC, Pigius commented on aws-ruby-cron-with-dynamodb/README.md
> +for deploying to the specific stage, let's say `staging` (those are defined in `config/deployment.yml`) do:
Great catch @pgrzesik fixed it!

2021-06-14 11:22 UTC, pgrzesik approved these changes
Thanks @Pigius - great job :clap:

2021-06-14 11:22 UTC, merged