add google ruby example
serverless/examples pull request #675
Opened 2022-01-06 02:07 UTC by colemanja91

An example of a Google Cloud Functions Ruby function.

2022-01-06 21:59 UTC, pgrzesik commented
Hey @colemanja91 - thanks a lot, could you please revert the unrelated changes from README? Sorry for the trouble

2022-01-06 23:17 UTC, colemanja91 commented
@pgrzesik Done!

2022-01-07 09:54 UTC, pgrzesik approved these changes
Looks good in general, I have only minor suggestion and we're good to go 👍

2022-01-07 09:54 UTC, pgrzesik commented on google-ruby-simple-http-endpoint/package.json
> +    "serverless-google-cloudfunctions": "^4.5.0"
I think it would be better to have it as `devDependencies`

2022-01-07 09:54 UTC, pgrzesik commented on google-ruby-simple-http-endpoint/package.json
> +  "main": "app.rb",
let's remove `main` here

2022-01-07 09:55 UTC, pgrzesik requested changes
Sorry, I've clicked on 'approve' by mistake

2022-01-07 15:39 UTC, pgrzesik approved these changes
Thanks a lot @colemanja91 🙇

2022-01-07 15:39 UTC, merged