Update framework versions to v3
serverless/examples pull request #747
Opened 2023-03-28 13:45 UTC by meddy672

I have updated the frameworkVersion to v3 and fixed the runtimes issues.

2023-03-28 16:02 UTC, medikoo requested changes
@meddy672 thank you! It looks great, there's just one file in the PR which shouldn't be there

2023-03-28 16:02 UTC, medikoo commented on yarn.lock
Let's not introduce this file

2023-03-28 16:17 UTC, meddy672 commented on yarn.lock
> Let's not introduce this file

I have removed the `yarn.lock` file at the root directory level.

2023-03-29 07:02 UTC, medikoo reviewed
Thanks @meddy672 I have just one last question towards Python version

2023-03-29 07:02 UTC, medikoo commented on openwhisk-python-simple-http-endpoint/serverless.yml
> +  runtime: python3.7
Why not `python3.9` ?

2023-03-29 10:01 UTC, meddy672 commented on openwhisk-python-simple-http-endpoint/serverless.yml
> +  runtime: python3.7
> Why not `python3.9` ?

Sure I can update python to v3.9. Fix should be up shortly.

2023-03-29 10:42 UTC, merged